services:
    .siteviewonline.listener:
        class: aurelienazerty\siteviewonline\event\listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }